# 示例配置文件：config.yml
# 此文件用于配置飞书文档同步工具 feishu2md 的行为
# 复制此文件并重命名为 config.yml，然后根据需要修改配置

version: "1.0"
sync:
  # 输出目录
  output_dir: ./feishu_docs
  # 同步模式选项:
  # "clean_all": 清空重下 - 每次同步前清空输出目录，重新下载所有文档
  # "incremental": 增量更新 - 只下载新增或已更新的文档，跳过已存在且未变更的文档
  sync_mode: incremental
  # 并发下载数
  concurrent_downloads: 10
  # 是否按组织结构存储
  organize_by_group: true
  # 是否跳过图片下载
  skip_images: true
  # 是否使用飞书文档的原始标题名
  use_original_title: true

# 增量同步说明:
# - 当 sync_mode 为 "incremental" 时:
#   1. 如果配置中的文档在输出目录中不存在，则会下载
#   2. 如果文档已存在，会检查云端文档的 RevisionID 与本地元数据比较
#   3. 如果 RevisionID 不同，说明文档有更新，会重新下载
#   4. 如果 RevisionID 相同，跳过下载
# - 使用 --force 标志可以强制清空目录重新下载所有文档
# - 元数据文件存储在与文档相同的目录下，以 .文档名.meta 格式命名

# 文档列表：需要同步的飞书文档
# group 不填将直接保存到 output_dir 根目录
documents:
  # 普通文档 (markdown)
  - name: 示例文档1
    url: https://example.feishu.cn/wiki/EXAMPLE1

  # CSV 格式的表格
  - name: 示例表格_CSV
    type: csv
    url: https://example.feishu.cn/wiki/EXAMPLE2

  # XLSX 格式的表格
  - name: 示例表格_XLSX
    type: xlsx
    url: https://example.feishu.cn/wiki/EXAMPLE3
